@startuml
!define RECTANGLE class

RECTANGLE SeedNode {
  highavaiablity-bool
  highPerformance-bool

}


RECTANGLE Mqtt_Network {
  + defineBroker(port: int)
  + connectCallback()
  + disconnectCallback()
  + receiveMessageCallback()
  + handleVotingMessage()
  + handleAdminPrompted()
  + handleLogsMessage()
  + handleAliveMessage()
  + handleDepartureMessage()
  + handleJoinRequest()
  + handleNodeHardwareInfo()
  + promoteMaster(): bool-true
  + backupMaster(): bool-false
}

RECTANGLE Vote {
  - voter: SeedNode 
  - candidate: Master
  - timestamp: DateTime
  + selectAdminNode(): SeedNode 
  + getVoter(): SeedNode 
  + getCandidate(): Master
  + getTimestamp(): DateTime
  + publishMaster():bool
}



RECTANGLE Node {
  + publishAliveMessage()
  + publishDepartureMessage()
  + publishJoinRequest()
  + isTraining: bool
  + publishHardwareInfo()
}

RECTANGLE Master {
  + Updated_backupLog()
  + save_backupLog()
  + send_logs_to_BackupMaster()
  + voteForMaster(): Vote
  + monitorLogs()
  + promoteToMaster(): bool
  + grantPermissionToNode(): bool
}

RECTANGLE BackupMaster {
  + GetLogFile()
  + makeBackupCopylogfile()
  + CheckpromoteToMaster(): bool
}


@enduml
wrte description and do not specify plant UML