@startuml
start
:topic='Connected',broker='localhost';
:userConnect to mqtt;
:Identify Participants in connected mqtt;
: VotingParticipants(random Participant);
if (Determine Winner) then (Yes)
  :Winner Node Becomes Aggregator;
  :Send IPFS Link for Data Storage;

endif
:Start DFL Using MQTT;



repeat
  :Train Machine Learning Model;
  :Send Model to Aggregator;
  :Aggregator Receives Models;
  :Aggregate Models;
  :Send Global Model to Others;

@enduml
