@startuml

participant "Node" as Node
participant "Mqtt_Network" as MqttNetwork
participant "Super_Node" as SuperNode
participant "Vote" as Voting
participant "Administrator" as Admin
participant "BackupAdministrator" as BackupAdmin

note right of Node: Node initiates\ncommunication

activate SuperNode
SuperNode -> Voting: selectAdminNode()
activate Voting
Voting -> SuperNode: getVoter(), getCandidate()
Voting -> Admin: voteForAdministrator()
activate Admin
Admin --> Voting: respondToVote()
deactivate Admin
Voting -> SuperNode: publishAdministrator()
deactivate Voting
deactivate SuperNode

activate Node
Node -> MqttNetwork: publishJoinRequest()
activate MqttNetwork
MqttNetwork -> SuperNode: handleJoinRequest()
activate SuperNode
SuperNode --> MqttNetwork: respondToJoinRequest()
deactivate SuperNode
MqttNetwork -> Node: acknowledgeJoinRequest()

Node -> MqttNetwork: publishAliveMessage()
MqttNetwork -> Admin: Updated_backupLog()

Node -> MqttNetwork: publishDepartureMessage()
MqttNetwork -> Admin: Updated_backupLog()

Node -> MqttNetwork: isTraining: bool
MqttNetwork -> Admin: Updated_backupLog()

Node -> MqttNetwork: publishHardwareInfo()
deactivate MqttNetwork
deactivate Node

activate Admin
Admin -> Node: grantPermissionToNode()
activate Node
Node -> Admin: acknowledgePermission()
deactivate Node
deactivate Admin

activate SuperNode
SuperNode -> MqttNetwork: handleAdminPrompted()
activate MqttNetwork
MqttNetwork -> BackupAdmin: CheckpromoteToAdministrator()
activate BackupAdmin
BackupAdmin -> BackupAdmin: GetLogFile()
BackupAdmin -> Admin: Updated_backupLog()
activate Admin
Admin -> BackupAdmin: send_logs_to_BackupAdministrator()
deactivate Admin
BackupAdmin -> MqttNetwork: promoteAdministrator()
deactivate BackupAdmin
MqttNetwork -> SuperNode: respondToAdminPromotion()
deactivate MqttNetwork
deactivate SuperNode

activate Node
Node -> MqttNetwork: publishAliveMessage()
activate MqttNetwork
MqttNetwork -> SuperNode: handleAliveMessage()
activate SuperNode
SuperNode --> MqttNetwork: respondToAliveMessage()
deactivate SuperNode
deactivate MqttNetwork
deactivate Node

@enduml
