@startuml Combined_Process

participant "Aggregator" as Aggregator
participant "Nodes" as Nodes
participant "IPFS" as IPFS
participant "User" as User
participant "MqttCluster" as MqttCluster
participant "ClusterNode" as ClusterNode
participant "Log" as Log

note left: Start Training Process

User -> MqttCluster: Request Training Node
MqttCluster -> Log: Log Event - Training Request Received
MqttCluster -> User: User Granted
Log -> MqttCluster: Log Event - User Granted Training
User -> MqttCluster: Check Node Availability
MqttCluster -> User: Node Available
MqttCluster -> Log: Log Event - Node Available
MqttCluster -> Aggregator: Initialize MqttOperations
Aggregator -> MqttCluster: Number of nodes to perform operation
Log -> MqttCluster: Log Event - Mqtt Operations Initialized

alt Aggregator Selection
note left: Aggregator Selection

    Aggregator -> ClusterNode: Aggregator Selection Process
    Log -> Aggregator: Log Event - Aggregator Selected
else
    Aggregator -> ClusterNode: Default Selection
    Log -> Aggregator: Log Event - Default Aggregator Selected
end
ClusterNode -> MqttCluster: Join Cluster
Aggregator -> ClusterNode: Identify Aggregator
ClusterNode -> ClusterNode: Training Process
Log -> ClusterNode: Log Event - ClusterNode Joined and Training Started




note left: Start Training Process

Aggregator -> Nodes: Start Training
Nodes -> Nodes: Model Training
loop Training Iterations
    Nodes -> Nodes: Train Model
end
Nodes -> IPFS: Store Model
IPFS -> Nodes: Get Model Hash
Nodes -> Aggregator: Send Model Hash
Aggregator -> Aggregator: Wait for all Model Hashes
loop Collect Model Hashes
    Nodes -> Aggregator: Model Hash Ready
end
Aggregator -> IPFS: Get All Models
IPFS --> Aggregator: Models
Aggregator -> Aggregator: Aggregate Models

Aggregator -> IPFS: Store Global Model
Aggregator -> Nodes: Send Global Model Hash to IPFS
Nodes -> IPFS: Store Global Model Hash
Nodes -> IPFS: Log Status (Missing Model to IPFS)
Aggregator -> Aggregator: Monitor Convergence
Aggregator -> Nodes: Update Model/Iteration Progress
alt Stop Criteria
    Aggregator -> Nodes: Stop Training
    Nodes -> Aggregator: Model Sharing
end
Aggregator -> IPFS: Get Global Model
IPFS --> Aggregator: Global Model
Nodes -> IPFS: Get Global Model Hash
IPFS --> Nodes: Global Model
Nodes -> Nodes: Update Weights with Global Model



@enduml
